name: Docker Image CI

on:
  push:
    branches: main
#  release:
#    types: [published]
    
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
#    - name: Checkout repo
#      uses: actions/checkout@v2
#    - name: build and push
#      uses: docker/build-push-action@v2
#      with:
#        registry: ghcr.io
#        username: "vforwater"
#        password: ${{ secrets.PAT }}
#        repository: vforwater/tbr_moving_dispersion
#        tags: latest,${{ github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  vforwater/tbr_moving_dispersion:latest, vforwater/tbr_moving_dispersion:${{ github.ref_name }}